name: lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint source code with eslint
        run: npm run lint

  prettier:
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint source code with eslint
        run: npm run check:format
